export {default as robot} from "./robot.png";
export {default as robot2} from "./robot-2.jpg";
export {default as profile1} from "./profile-1.png";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as profile7} from "./profile-7.jpeg";
export {default as profile8} from "./profile-8.jpeg";
export {default as profile9} from "./profile-9.jpeg";
export {default as profile10} from "./profile-10.jpeg";

export {default as amazon} from './logos/amazon.png'
export {default as facebook} from './logos/facebook.png'
export {default as google} from './logos/google.png'
export {default as linkedin} from './logos/linkedin.png'
export {default as microsoft} from './logos/microsoft.png'
export {default as netflix} from './logos/netflix.png'
export {default as paypal} from './logos/paypal.png'
export {default as samsung} from './logos/samsung.png'
export {default as skype} from './logos/skype.png'
export {default as whatsapp} from './logos/whatsapp.png'